### ISSUE TITLE
Chokes on non-ASCII chars

### ISSUE THREAD

**Issue by a168290** [catap/namebench#1]
Seen with Master branch on 02 Mar 2015:

- Error querying City Telecom [203.80.96.10:regional,country_hk,ipv4,nearby]: www.megaclick.com.: Timeout
- Error querying 和記環球電訊 HGC (2) [210.0.255.251:regional,country_hk,ipv4,nearby]: www.megaclick.com.: Timeout
- Benchmark finished.
Traceback (most recent call last):
  File "./namebench.py", line 77, in <module>
    namebench.Execute()
  File "/tmp/namebench-master/libnamebench/cli.py", line 126, in Execute
    self.RunAndOpenReports()
  File "/tmp/namebench-master/libnamebench/cli.py", line 81, in RunAndOpenReports
    print "\n%s\n" % self.reporter.CreateReport(format='ascii')
  File "/tmp/namebench-master/libnamebench/reporter.py", line 253, in CreateReport
    csv_link=csv_link
  File "/tmp/namebench-master/nb_third_party/jinja2/environment.py", line 868, in render
    return self.environment.handle_exception(exc_info, True)
  File "templates/ascii.tmpl", line 3, in top-level template code
    {% for item in lowest_latency %}{{ "%-16.16s %s %2.5f\n"|format(item[0], item[1], item[2]) }}{% endfor %}
  File "/tmp/namebench-master/nb_third_party/jinja2/filters.py", line 443, in do_format
    return soft_unicode(value) % (kwargs or args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
(

**Comment by catap** [comment]
Good day!

Sorry for long response.

This issue looks like a timeout. The reason of this issue is temporary network issue for example.
